# Generated by Django 4.2.27 on 2026-02-01 14:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_alter_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_stock', models.PositiveIntegerField(default=0)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category')),
            ],
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'category_id'), name='unique_product_name_per_category'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.Index(fields=['category_id'], name='idx_category_id'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.Index(fields=['price'], name='price_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.Index(fields=['created_at'], name='created_at_brin_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.Index(fields=['updated_at'], name='updated_at_brin_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='price_non_negative'),
        ),
    ]
